# Generated by Django 2.2.12 on 2020-08-26 19:22

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('lucknow', django.db.models.manager.Manager()),
            ],
        ),
    ]
